- name: Install nginx
  hosts: web
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
        state: latest
        update_cache: yes
    - name: Start nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted