- name: Install nginx
  hosts: all         #Installs on all ip's present in each group#
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
        state: latest
        update_cache: yes
    - name: Start nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted


- name: Install nginx
  hosts: all         #Installs on all ip's present in each group#
  become: yes
  roles:
    - sample-nginx