- name: print the hello-world using role
  ansible.builtin.debug:
    msg: hello-world

- name: print the variable from role
  ansible.builtin.debug:
    msg: url is "{{URL}}"

- name: print the variable from play level
  ansible.builtin.debug:
    msg: url_play is "{{ URL_Play}}"
